"""update_user

Revision ID: 63ecab91945f
Revises: d40f40264827
Create Date: 2023-10-06 06:31:15.036911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63ecab91945f"
down_revision = "d40f40264827"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_user", sa.Column("firstname", sa.String(), nullable=False))
    op.add_column("auth_user", sa.Column("lastname", sa.String(), nullable=False))
    op.add_column("auth_user", sa.Column("phone", sa.String(), nullable=False))
    op.add_column("auth_user", sa.Column("avatar", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "avatar")
    op.drop_column("auth_user", "phone")
    op.drop_column("auth_user", "lastname")
    op.drop_column("auth_user", "firstname")
    # ### end Alembic commands ###
